challenge:
  api_key: "challenge_api_key"
  docker_ulimit: 32768
  bot_timeout: 10
  repeated_framework_count: 3
  framework_images:
    - name: seleniumbase
      image: abdibekbolot/automation_frameworks@sha256:2538c53aed8ec17e32249b54f6da191954874d3285dac228e1e01791d8455d1c
    - name: seleniumdriverless
      image: abdibekbolot/automation_frameworks@sha256:da3f48811c368da2e49145c579eda7c541d632af4995495b9109838e4fa654d7
    - name: pydoll
      image: abdibekbolot/automation_frameworks@sha256:e94a907b7ea809223a2e5b5884fd92b3ea1ef851e254655eeb4140ba6712e694
    - name: patchright
      image: abdibekbolot/automation_frameworks@sha256:8f04be5fb91b00e7af9b8e227bfad187c98ec21c9ad0fce76f7ffdbae877b218
    - name: zendriver
      image: abdibekbolot/automation_frameworks@sha256:9cc4c2d30033aad72bb855a6ea972894f432cd274d61097d5440b6cbd40f7372
    - name: nodriver
      image: abdibekbolot/automation_frameworks@sha256:4d1ac3e2847286cf56be0a71c4a2cc0c1ecd0eab0886a0978f02330f007fd7a6
    - name: camoufox
      image: abdibekbolot/automation_frameworks@sha256:f4dc8fada71dbca4564739862769c6452e0e8b0076c7b181ef711047b9872228
    - name: botasaurus
      image: abdibekbolot/automation_frameworks@sha256:723875c82fcef252ff3e9720cd291ead49d6b1bcd7fe6c8872223843d2d14a26
    - name: puppeteerextra
      image: abdibekbolot/automation_frameworks@sha256:d87bcbf650a9996a7aee8cea3b7e972279b084842f82007b789bffa3bd7dda1b
